# Generated by Django 4.1.2 on 2022-11-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apix', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
